package com.spirit.pageObjects;

import java.util.List;

/***********************************************************************************************
 //Class Name		: HomePage
 //Description		: Method is starting point of automation execution.
 //                    1.Extended Parallel Executor is used to run features files in parallel.
 //					  2.Extended Reporting is used to generate the HTML and PDF reports.
 //					  3.Usage report is used to calculate percentage amount of Steps reused.
 //					  4.Reports files are generated in date format folders.
 //					  5.Reports are generated with time stamp and prefixed with EPIC.
 //					  6.Retry Counter is added as 'retryCount'.
 //					  7.Grid Node count is added as 'threadsCount'.
 //					  8.All the reports are generated by using json file created after execution.
 //					  9.Mail is send to all recipient after reports are generated.
 //Input Arguments	: NA
 //Return			: NA
 //Created By 		: Salim Ansari
 //Created On 		: 04-Feb-2019
 //Reviewed By		: TBD
 //Reviewed On		: TBD
 //**********************************************************************************************/

/*
ifr      -  iframe
btn      -  Button
chkbx    -  CheckBox
chklst   -  CheckBoxList
drpdwn   -  DropDownList
grdvew   -  GridView
hyrlnk   -  Hyperlink
img      -  Image
imgbtn   -  ImageButton
lbl      -  Label
lnkbtn   -  LinkButton
lnk      -  Link
lstbx    -  ListBox
lit      -  Literal
pnl      -  Panel
ph       -  PlaceHolder
rdbtn    -  RadioButton
rdbtnlst -  RadioButtonList
txtbx       Textbox
txt      -  Text
 */

import javafx.scene.web.WebView;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;

public class HomePage {


	//private WebDriver driver;

	public HomePage(WebDriver driver) {
		//this.driver = driver;
		PageFactory.initElements(driver, this);
	}

	//*******************************************************************
	//*******************Top Left Header Home Page**********************
	//*******************************************************************
	public final String xpath_SpiritLogoImage = "//img[@class='logo']";
	@FindBy(xpath=xpath_SpiritLogoImage)
	private WebElement img_SpiritLogo;

	public final String xpath_OptionalServiceLink = "//a[contains(text(),'Optional Services') or contains(text(),'Opciones y Extras')]";
	@FindBy(xpath=xpath_OptionalServiceLink)
	private WebElement lnk_OptionalService;

	//*******************************************************************
	//*******************Top Right Header Home Page**********************
	//*******************************************************************
	public final String xpath_SignInListLink = "//a[contains(text(),'Sign-In') or contains(text(),'Ingresar')]";
	@FindBy(xpath=xpath_SignInListLink)
	private List<WebElement> lnk_SignInList;

	public final String xpath_UsericonImage = "//i[@class='icon-user']";
	@FindBy(xpath=xpath_UsericonImage)
	private List<WebElement> Img_Usericon;

	public final String xpath_IconBarImage = "//span[@class='icon-bars']";
	@FindBy(xpath=xpath_IconBarImage)
	private WebElement img_IconBar;

	public final String xpath_SelectedLanguageLink = "//a[@aria-label='Language']";
	@FindBy(xpath=xpath_SelectedLanguageLink)
	private List<WebElement> lnk_SelectedLanguage;

	public final String xpath_HelpListLink = "//a[contains(text(),'Help') or contains(text(),'Ayuda')]";
	@FindBy(xpath=xpath_HelpListLink)
	private List<WebElement> lnk_HelpList;

	public final String xpath_ContactUsListLink = "//a[contains(text(),'Contact Us') or contains(text(),'Comuníquese con Nosotros')]";
	@FindBy(xpath=xpath_ContactUsListLink)
	private List<WebElement> lnk_ContactUsList;

	public final String xpath_DealsListLink = "//a[contains(text(),'Deals') or contains(text(),'Ofertas')]";
	@FindBy(xpath=xpath_DealsListLink)
	private List<WebElement> lnk_DealsList;

	public final String xpath_$9FareClubListLink = "//a[contains(text(),'$9 Fare Club®')]";
	@FindBy(xpath=xpath_$9FareClubListLink)
	private List<WebElement> lnk_$9FareClubList;

	public final String xpath_Spirit101ListLink = "//a[contains(text(),'Spirit 101')]";
	@FindBy(xpath=xpath_Spirit101ListLink)
	private List<WebElement> lnk_Spirit101List;

	public final String xpath_DestinationsListLink = "//a[contains(text(),'Destinations') or contains(text(),'Destinos')]";
	@FindBy(xpath=xpath_DestinationsListLink)
	private List<WebElement> lnk_DestinationsList;

	//*******************************************************************
	//*******************TAB List Home Page******************************
	//*******************************************************************
	public final String xpath_SearchWidgetPanel = "//div[@id='book-panel']";
	@FindBy(xpath=xpath_SearchWidgetPanel)
	private WebElement pnl_SearchWidget;

	public final String xpath_BookPathLink = "//a[@id='book' or @aria-label='Book']";
	@FindBy(xpath=xpath_BookPathLink)
	private List<WebElement> lnk_BookPath;

	public final String xpath_MyTripPathLink = "//a[@id='mytrips' or @aria-label='My Trips']";
	@FindBy(xpath=xpath_MyTripPathLink)
	private List<WebElement> lnk_MyTripPath;

	public final String xpath_CheckInPathLink = "//a[@id='checkin' or @aria-label='Check-In']";
	@FindBy(xpath=xpath_CheckInPathLink)
	private List<WebElement> lnk_CheckInPath;

	public final String xpath_FlightStatusPathLink = "//a[@id='flightstatus' or @aria-label='Flight Status']";
	@FindBy(xpath=xpath_FlightStatusPathLink)
	private List<WebElement> lnk_FlightStatusPath;

	//*******************************************************************
	//*******************Trip Tab Home Page******************************
	//*******************************************************************
	public final String xpath_MyTripConfirmationCodeLink = "//a[contains(text(),'Confirmation Code') or contains(text(),'Clave de Confirmación')]";
	@FindBy(xpath=xpath_MyTripConfirmationCodeLink)
	private WebElement 	lnk_MyTripConfirmationCode;

	public final String xpath_MyTripConfirmationCodeChevronLink = "//a[contains(text(),'Confirmation Code') or contains(text(),'Clave de Confirmación')]//app-chevron/..";
	@FindBy(xpath=xpath_MyTripConfirmationCodeChevronLink)
	private WebElement lnk_MyTripConfirmationCodeChevron;

	public final String xpath_MyTripConfirmationCodeText = "//a[contains(text(),'Confirmation Code') or contains(text(),'Clave de Confirmación')]/..";
	@FindBy(xpath=xpath_MyTripConfirmationCodeText)
	private WebElement txt_MyTripConfirmationCode;

	public final String xpath_MyTripLastNameTextBox = "//input[@id='my-trips-lastName']";
	@FindBy(xpath=xpath_MyTripLastNameTextBox)
	private WebElement txtbx_MyTripLastName;

	public final String xpath_MyTripConfirmationCodeTextBox = "//input[@id='my-trips-recordLocator']";
	@FindBy(xpath=xpath_MyTripConfirmationCodeTextBox)
	private WebElement txtbx_MyTripConfirmationCode;

	public final String xpath_MyTripContinueButton = "//button[contains(@class,'primary') and (contains(text(),'continue') or contains(text(),'continuar'))]";
	@FindBy(xpath=xpath_MyTripContinueButton)
	private WebElement btn_MyTripContinue;

	//*******************************************************************
	//*******************CheckIn Tab Home Page***************************
	//*******************************************************************
	public final String xpath_CheckInLastNameTextBox= "//input[@id='check-in-lastName']";
	@FindBy(xpath=xpath_CheckInLastNameTextBox)
	private WebElement txtbx_CheckInLastName;

	public final String xpath_CheckInConfirmationCodeTextBox = "//input[@id='check-in-recordLocator']";
	@FindBy(xpath=xpath_CheckInConfirmationCodeTextBox)
	private WebElement txtbx_CheckInConfirmationCode;

	public final String xpath_WhereToFindYourConfirmationCodeLink = "//p[@class='increase-pb']/a";
	@FindBy(xpath=xpath_WhereToFindYourConfirmationCodeLink)
	private WebElement lnk_WhereToFindYourConfirmationCode;

	public final String xpath_CheckInButton = "//button[contains(text(),'Check-In') or contains(text(),'Registrarme ')]";
	@FindBy(xpath=xpath_CheckInButton)
	private WebElement btn_CheckIn;

	public final String xpath_ReservationNotFoundHeaderText = "//h2[contains(text(),'Reservation Not Found') or contains(text(),'No Se Encontró La Reservación')]";
	@FindBy(xpath=xpath_ReservationNotFoundHeaderText)
	private WebElement txt_ReservationNotFoundHeader;

	public final String xpath_ReservationNotFoundBodyText = "//div[@class='modal-body']//p[contains(text(),'We are unable to locate the itinerary') or contains(text(),'No podemos localizar el itinerario')]";
	@FindBy(xpath=xpath_ReservationNotFoundBodyText)
	private WebElement txt_ReservationNotFoundBody;

	public final String xpath_ReservationNotFoundCloseButton = "//div[@class='modal-body']//button[contains(text(),'Close')]";
	@FindBy(xpath=xpath_ReservationNotFoundCloseButton)
	private WebElement btn_ReservationNotFoundClose;

	//*******************************************************************
	//*******************FlightStatus Tab Home Page**********************
	//*******************************************************************
	public final String xpath_CheckByFlightNumberLabel = "//span[contains(text(),'Check By Flight Number') or contains(text(),'Revisar por Número de Vuelo')]";
	@FindBy(xpath=xpath_CheckByFlightNumberLabel)
	private WebElement lbl_CheckByFlightNumber;

	public final String xpath_CheckByDestinationLabel = "//span[contains(text(),'Check By Destination') or contains(text(),'Revisar por Destino')]";
	@FindBy(xpath=xpath_CheckByDestinationLabel)
	private WebElement lbl_CheckByDestination;

	public final String xpath_FlightStatusSubHeaderText = "//p[contains(@class,'increase-pb')]";
	@FindBy(xpath=xpath_FlightStatusSubHeaderText)
	private WebElement txt_FlightStatusSubHeader;

	public final String xpath_FlightStatusFlightNumberTextBox= "//input[@id='flightNumber']";
	@FindBy(xpath=xpath_FlightStatusFlightNumberTextBox)
	private WebElement txtbx_FlightStatusFlightNumber;

	public final String xpath_FlightStatusFlightNumberImage = "//label[@for='flightNumber']/i";
	@FindBy(xpath=xpath_FlightStatusFlightNumberImage)
	private WebElement img_FlightStatusFlightNumber;

	public final String xpath_FlightStatusDateDropDown = "//select[@id='date' or @name='date']";
	@FindBy(xpath=xpath_FlightStatusDateDropDown)
	private WebElement drpdwn_FlightStatusDate;

	public final String xpath_FlightStatusDateImage = "//label[@for='date']/i";
	@FindBy(xpath=xpath_FlightStatusDateImage)
	private WebElement img_FlightStatusDate;

	public final String xpath_FlightStatusCheckStatusButton = "//button[text()='Check Status']";
	@FindBy(xpath=xpath_FlightStatusCheckStatusButton)
	private WebElement btn_FlightStatusCheckStatus;

	public final String xpath_FlightStatusStationAdvisoryText = "//div[contains(@class,'station-advisory')]//p";
	@FindBy(xpath=xpath_FlightStatusStationAdvisoryText)
	private WebElement txt_FlightStatusStationAdvisory;

	public final String xpath_FlightStatusStationAdvisoryLearnMoreLink = "//div[contains(@class,'station-advisory')]//p/a";
	@FindBy(xpath=xpath_FlightStatusStationAdvisoryLearnMoreLink)
	private WebElement lnk_FlightStatusStationAdvisoryLearnMore;

	public final String xpath_FlightStatusDateText = "//div[contains(text(),',')]";
	@FindBy(xpath=xpath_FlightStatusDateText)
	private WebElement txt_FlightStatusDate;

	public final String xpath_FLightStatusFlightNumberText = "//div[text()='Flight']/following-sibling::div";
	@FindBy(xpath=xpath_FLightStatusFlightNumberText)
	private List<WebElement> txt_FLightStatusFlightNumber;

	public final String xpath_FlightStatusOnTimeText = "//div[contains(text(),'On Time')]";
//	public final String xpath_FlightStatusOnTimeText = "//div[text()='On Time']";
	@FindBy(xpath=xpath_FlightStatusOnTimeText)
	private List<WebElement> txt_FlightStatusOnTime;

	public final String xpath_FlightStatusGetUpdateButton = "//button[contains(@aria-describedby,'aria-flight-number')]";
	@FindBy(xpath=xpath_FlightStatusGetUpdateButton)
	private List<WebElement> btn_FlightStatusGetUpdate;

	public final String xpath_GetUpdateHeaderText = "//button[contains(@aria-describedby,'aria-flight-number')]/../following-sibling::div//p";
	@FindBy(xpath=xpath_GetUpdateHeaderText)
	private List<WebElement> txt_GetUpdateHeader;

	public final String xpath_GetUpdateEmailLabel = "//button[contains(@aria-describedby,'aria-flight-number')]/../following-sibling::div//label";
	@FindBy(xpath=xpath_GetUpdateEmailLabel)
	private List<WebElement> lbl_GetUpdateEmail;

	public final String xpath_GetUpdateEmailTextBox = "//button[contains(@aria-describedby,'aria-flight-number')]/../following-sibling::div//input";
	@FindBy(xpath=xpath_GetUpdateEmailTextBox)
	private List<WebElement> txtbx_GetUpdateEmail;

	public final String xpath_GetUpdateCancelButton = "//button[contains(@aria-describedby,'aria-flight-number')]/../following-sibling::div//button[@type='reset']";
	@FindBy(xpath=xpath_GetUpdateCancelButton)
	private List<WebElement> btn_GetUpdateCancel;

	public final String xpath_GetUpdateGetUpdateButton = "//button[contains(@aria-describedby,'aria-flight-number')]/../following-sibling::div//button[@type='submit']";
	@FindBy(xpath=xpath_GetUpdateGetUpdateButton)
	private List<WebElement> btn_GetUpdateGetUpdate;

	public final String xpath_FlightStatusCollapseShowLink = "//span[contains(@class,'lineNumberBackDrop')]//following-sibling::div//i";
	@FindBy(xpath=xpath_FlightStatusCollapseShowLink)
	private List<WebElement> lnk_FlightStatusCollapseShow;

	public final String xpath_FlightStatusCollapseShowDepartureText = "//span[contains(@class,'lineNumberBackDrop')]//following-sibling::div//div[@class='collapse show']/div/div[1]//div";
	@FindBy(xpath=xpath_FlightStatusCollapseShowDepartureText)
	private List<WebElement> txt_FlightStatusCollapseShowDeparture;

	public final String xpath_FlightStatusCollapseShowArrivalText = "//span[contains(@class,'lineNumberBackDrop')]//following-sibling::div//div[@class='collapse show']/div/div[2]//div";
	@FindBy(xpath=xpath_FlightStatusCollapseShowArrivalText)
	private List<WebElement> txt_FlightStatusCollapseShowArrival;

	public final String xpath_FlightStatusCollapseShowTimeText = "//span[contains(@class,'lineNumberBackDrop')]//following-sibling::div//div[@class='collapse show']/div/div[3]//div";
	@FindBy(xpath=xpath_FlightStatusCollapseShowTimeText)
	private List<WebElement> txt_FlightStatusCollapseShowTime;

	public final String xpath_FlightStatusSelectedDepartureAirportText = "(//i[@class='icon-primary-plane icon-custom mr-3']//following::p)[1]";
	@FindBy(xpath=xpath_FlightStatusSelectedDepartureAirportText)
	private WebElement txt_FlightStatusSelectedDepartureAirport;

	public final String xpath_FlightStatusSelectedArrivalAirportText = "(//i[@class='icon-primary-plane icon-custom mr-3']//following::span)[1]";
	@FindBy(xpath=xpath_FlightStatusSelectedArrivalAirportText)
	private WebElement txt_FlightStatusSelectedArrivalAirport;

	//***********************************************************
	//*******************your Confirmation Code Popup************
	//***********************************************************

	public final String xpath_CheckInHowToFindConfirmationCodeLink = "//a[contains(text(),'Where to find your Confirmation Code .') or contains(text(),'Dónde encontrar su Clave de Confirmación .')]";
	@FindBy(xpath=xpath_CheckInHowToFindConfirmationCodeLink)
	private WebElement lnk_CheckInHowToFindConfirmationCode;

	public final String xpath_PopUpCrossButtonButton = "//i[@class='icon-close']";
	@FindBy(xpath=xpath_PopUpCrossButtonButton)
	private WebElement btn_PopUpCrossButton;

	public final String xpath_YouConfirmationPopupHeaderText = "//h2[contains(text(),'Your Confirmation Code') or contains(text(),'Dónde encontrar su Clave de Confirmación .')]";
	@FindBy(xpath=xpath_YouConfirmationPopupHeaderText)
	private WebElement txt_YouConfirmationPopupHeader;

	public final String xpath_YouConfirmationPopupImageImage = "//img[@class='img-responsive']";
	@FindBy(xpath=xpath_YouConfirmationPopupImageImage)
	private WebElement img_YouConfirmationPopupImage;

	public final String xpath_ExpediaConfirmationPopUp = "//a[contains(text(),'Expedia')]";
	@FindBy(xpath=xpath_ExpediaConfirmationPopUp)
	private WebElement lnk_ExpediaConfirmationPopUp;

	public final String xpath_PricelineConfirmationPopUpLink = "//a[contains(text(),'Priceline')]";
	@FindBy(xpath=xpath_PricelineConfirmationPopUpLink)
	private WebElement lnk_PricelineConfirmationPopUp;

	public final String xpath_CheapoairConfirmationPopUpLink = "//a[contains(text(),'Cheapoair')]";
	@FindBy(xpath=xpath_CheapoairConfirmationPopUpLink)
	private WebElement lnk_CheapoairConfirmationPopUp;

	public final String xpath_OrbitzConfirmationPopUpLink = "//a[contains(text(),'Orbitz')]";
	@FindBy(xpath=xpath_OrbitzConfirmationPopUpLink)
	private WebElement lnk_OrbitzConfirmationPopUp;

	public final String xpath_SpiritConfirmationPopUpLink = "//li[@class='ng-star-inserted']//a[contains(text(),'Spirit')]";
	@FindBy(xpath=xpath_SpiritConfirmationPopUpLink)
	private WebElement lnk_SpiritConfirmationPopUp;

	//*******************************************************************
	//*******************Login Popup Home Page***************************
	//*******************************************************************
	public final String xpath_UserNameHeaderText = "//label[@for='username']";
	@FindBy(xpath=xpath_UserNameHeaderText)
	private WebElement txt_UserNameHeader;

	public final String xpath_UserNameTextBox= "//input[@id='username']";
	@FindBy(xpath=xpath_UserNameTextBox)
	private WebElement txtbx_UserName;

	public final String xpath_PasswordHeaderText = "//label[@for='password']";
	@FindBy(xpath=xpath_PasswordHeaderText)
	private WebElement txt_PasswordHeader;

	public final String xpath_PasswordTextBox = "//input[@id='password']";
	@FindBy(xpath=xpath_PasswordTextBox)
	private WebElement txtbx_Password;

	public final String xpath_ResetPasswordButton = "//input[@id='password']/following-sibling::button";
	@FindBy(xpath=xpath_ResetPasswordButton)
	private WebElement btn_ResetPassword;

	public final String xpath_LoginButton = "//button[contains(text(),'Log In') or contains(text(),'Inicia Sesión')]";
	@FindBy(xpath=xpath_LoginButton)
	private WebElement btn_Login;

	public final String xpath_SignUpNowLink = "//a[contains(text(),'Sign Up Now') or contains(text(),'Inscríbirme')]";
	@FindBy(xpath=xpath_SignUpNowLink)
	private WebElement lnk_SignUpNow;

	public final String xpath_NewPasswordText = "//label[@for='passwordNew']";
	@FindBy(xpath=xpath_NewPasswordText) //Added by Anthony
	private WebElement txt_NewPassword;

	public final String id_NewPasswordTextBox = "passwordNew";
	@FindBy(id=id_NewPasswordTextBox) //Added by Anthony
	private WebElement txtbx_NewPassword;

	public final String xpath_ConfirmNewPasswordText = "//label[@for='passwordConfirm']";
	@FindBy(xpath=xpath_ConfirmNewPasswordText) //Added by Anthony
	private WebElement txt_ConfirmNewPassword;

	public final String id_ConfirmNewPasswordTextBox = "passwordConfirm";
	@FindBy(id=id_ConfirmNewPasswordTextBox) //Added by Anthony
	private WebElement txtbx_ConfirmNewPassword;

	public final String xpath_LoginPopUpCloseButton = "//app-branded-modal//button[@class='close']";
	@FindBy(xpath = xpath_LoginPopUpCloseButton)
	private WebElement btn_LoginPopUpClose;

	//*******************************************************************
	//*******************Journey Type Home Page**************************
	//*******************************************************************
	public final String xpath_FlightBookingLink = "//a[@id='flight']";
	@FindBy(xpath=xpath_FlightBookingLink)
	private WebElement lnk_FlightBooking;

	public final String xpath_VacationBookingLink = "//a[@id='vacation']";
	@FindBy(xpath=xpath_VacationBookingLink)
	private WebElement lnk_VacationBooking;

	public final String xpath_CarBookingLink = "//a[@id='car']";
	@FindBy(xpath=xpath_CarBookingLink)
	private WebElement lnk_CarBooking;

	public final String xpath_HotelBookingLink = "//a[@id='hotel']";
	@FindBy(xpath=xpath_HotelBookingLink)
	private WebElement lnk_HotelBooking;

	public final String xpath_CruiseBookingLink = "//a[@id='cruise']";
	@FindBy(xpath=xpath_CruiseBookingLink)
	private WebElement lnk_CruiseBooking;

	//*******************************************************************
	//*********************Trip Type Home Page***************************
	//*******************************************************************
	public final String xpath_RoundTripRadioButton = "//span[contains(text(),'Round Trip') or contains(text(),'Viaje de ida y vuelta')]";
	@FindBy(xpath=xpath_RoundTripRadioButton)
	private WebElement rdbtn_RoundTrip;

	public final String xpath_RoundTripLabel = "//span[contains(text(),'Round Trip') or contains(text(),'Viaje de ida y vuelta')]/..";
	@FindBy(xpath=xpath_RoundTripLabel)
	private WebElement lbl_RoundTrip;

	public final String xpath_OneWayRadioButton = "//span[contains(text(),'One Way') or contains(text(),'Una vía')]";
	@FindBy(xpath=xpath_OneWayRadioButton)
	private WebElement rdbtn_OneWay;

	public final String xpath_OneWayLabel = "//label[@for='radio-oneWay']";
	@FindBy(xpath=xpath_OneWayLabel)
	private WebElement lbl_OneWay;

	public final String xpath_MultiCityRadioButton = "//span[contains(text(),'Multi-City') or contains(text(),'Multiciudad')]";
	@FindBy(xpath=xpath_MultiCityRadioButton)
	private WebElement rdbtn_MultiCity;

	public final String xpath_MultiCityLabel = "//span[contains(text(),'Multi-City') or contains(text(),'Multiciudad')]/..";
	@FindBy(xpath=xpath_MultiCityLabel)
	private WebElement lbl_MultiCity;

	//*******************************************************************
	//*********************Dollars or Miles Home Page********************
	//*******************************************************************

	public final String xpath_MilesLabel = "//label[contains(text(), 'Miles') or contains(text(),'Millas')]";
	@FindBy(xpath = xpath_MilesLabel)
	private WebElement lbl_Miles;

	//*******************************************************************
	//*********************Vacation Type Home Page***********************
	//*******************************************************************
	public final String xpath_FlightCarRadioButton = "//span[contains(text(),'Flight + Car') or contains(text(),'Vuelo + Auto')]";
	@FindBy(xpath=xpath_FlightCarRadioButton)
	private WebElement rdbtn_FlightCar;

	public final String xpath_FlightCarLabel = "//span[contains(text(),'Flight + Car') or contains(text(),'Vuelo + Auto')]/..";
	@FindBy(xpath=xpath_FlightCarLabel)
	private WebElement lbl_FlightCar;

	public final String xpath_FlightHotelRadioButton = "//span[contains(text(),'Flight + Hotel') or contains(text(),'Vuelo + Hotel')]";
	@FindBy(xpath=xpath_FlightHotelRadioButton)
	private WebElement rdbtn_FlightHotel;

	public final String xpath_FlightHotelLabel = "//span[contains(text(),'Flight + Hotel') or contains(text(),'Vuelo + Hotel')]/..";
	@FindBy(xpath=xpath_FlightHotelLabel)
	private WebElement lbl_FlightHotel;

	public final String xpath_FlightHotelCarRadioButton = "//span[contains(text(),'Flight + Hotel + Car') or contains(text(),'Vuelo+Hotel + Auto')]/..";
	@FindBy(xpath=xpath_FlightHotelCarRadioButton)
	private WebElement rdbtn_FlightHotelCar;

	public final String xpath_FlightHotelCarLabel = "//span[contains(text(),'Flight + Hotel + Car') or contains(text(),'Vuelo+Hotel + Auto')]/..";
	@FindBy(xpath=xpath_FlightHotelCarLabel)
	private WebElement lbl_FlightHotelCar;

	//*******************************************************************
	//***********************Airport Home Page***************************
	//*******************************************************************
	public final String xpath_AllLocationAirportText = "//button[contains(text(),'All Locations') or contains(text(),'Todas las Ubicaciones')]";
	@FindBy(xpath=xpath_AllLocationAirportText)
	private List<WebElement> txt_AllLocationAirport;

	public final String xpath_NorthAmericaAirportText = "//button[contains(text(),'North America') or contains(text(),'Norteamérica')]";
	@FindBy(xpath=xpath_NorthAmericaAirportText)
	private List<WebElement> txt_NorthAmericaAirport;

	public final String xpath_CentralAmericaAirportText = "//button[contains(text(),'Central America') or contains(text(),'Centromérica')]";
	@FindBy(xpath=xpath_CentralAmericaAirportText)
	private List<WebElement> txt_CentralAmericaAirport;

	public final String xpath_SouthAmericaAirportText = "//button[contains(text(),'South America') or contains(text(),'Sudamérica')]";
	@FindBy(xpath=xpath_SouthAmericaAirportText)
	private List<WebElement> txt_SouthAmericaAirport;

	public final String xpath_CaribbeanText = "//button[contains(text(),'Caribbean') or contains(text(),'El Caribe')]";
	@FindBy(xpath=xpath_CaribbeanText)
	private List<WebElement> txt_Caribbean;

	public final String xpath_DepartAirportTextBox = "//input[contains(@id,'riginStationCode')]";
	@FindBy(xpath=xpath_DepartAirportTextBox)
	private List<WebElement> txtbx_DepartAirport;

	public final String xpath_MultiCityDepartAirportTextBox = "//input[contains(@id,'originStationCode')]";
	@FindBy(xpath=xpath_MultiCityDepartAirportTextBox)
	private List<WebElement> txtbx_MultiCityDepartAirport;

	public final String xpath_ArrivalAirportTextBox = "//input[contains(@id,'estinationStationCode')]";
	@FindBy(xpath=xpath_ArrivalAirportTextBox)
	private List<WebElement> txtbx_ArrivalAirport;

	public final String xpath_MultiCityArrivalAirportTextBox= "//input[contains(@id,'destinationStationCode')]";
	@FindBy(xpath=xpath_MultiCityArrivalAirportTextBox)
	private List<WebElement> txtbx_MultiCityArrivalAirport;

	public final String xpath_AirportListText = "//button[contains(text(),'(') and contains(text(),')')]";
	@FindBy(xpath=xpath_AirportListText)
	private List<WebElement> txt_AirportList;

	public final String xpath_StationCloseButton = "//i[contains(@class,'station-close-btn')]";
	@FindBy(xpath=xpath_StationCloseButton)
	private List<WebElement> btn_StationClose;

	public final String xpath_MultiCityAddAnotherFlightButton = "//button[@aria-label='Add another flight']/i[@class='icon-plus']";
	@FindBy(xpath=xpath_MultiCityAddAnotherFlightButton)
	private WebElement btn_MultiCityAddAnotherFlight;

	public final String xpath_FromLabel = "//label[@for='flight-OriginStationCode']";
	@FindBy(xpath = xpath_FromLabel)
	private WebElement lbl_From;

	public final String xpath_FromArrowDownImage= "//label[@for='flight-OriginStationCode']/i";
	@FindBy(xpath = xpath_FromArrowDownImage)
	private WebElement img_FromArrowDown;

	public final String xpath_RoundTripArrowsImage = "(//i[@class='icon-roundtrip-arrows'])[1]";
	@FindBy(xpath = xpath_RoundTripArrowsImage)
	private WebElement img_RoundTripArrows;

	//*******************************************************************
	//*************************Date Home Page****************************
	//*******************************************************************
	public final String xpath_DateTextBox = "//input[contains(@id,'-Date')]";
	@FindBy(xpath=xpath_DateTextBox)
	private WebElement txtbx_Date;

	public final String xpath_MultiCityDateTextBox = "//input[contains(@id,'date')]";
	@FindBy(xpath=xpath_MultiCityDateTextBox)
	private List<WebElement>  txtbx_MultiCityDate;

	public final String xpath_CalenderHeaderText = "//div[contains(@class,'datepicker-head')]";
	@FindBy(xpath=xpath_CalenderHeaderText)
	private List<WebElement> txt_CalenderHeader;

	public final String xpath_PreviousMonthButton = "//button[@class='previous']";
	@FindBy(xpath=xpath_PreviousMonthButton)
	private List<WebElement> btn_PreviousMonth;

	public final String xpath_NextMonthButton = "//button[@class='next']";
	@FindBy(xpath=xpath_NextMonthButton)
	private List<WebElement> btn_NextMonth;

	public final String xpath_CalenderPanel = "//div[@class='bs-datepicker-container']";
	@FindBy(xpath = xpath_CalenderPanel)
	private List<WebElement> pnl_Calender;

	public final String xpath_CalendarHeaderValuesText = "//div[@class='bs-datepicker-head']//span";
	@FindBy(xpath= xpath_CalendarHeaderValuesText)
	private List<WebElement> txt_CalendarHeaderValues;

	public final String xpath_CalendarMonthDatesText = "//div[@class='bs-datepicker-body']//tbody";
	@FindBy(xpath=xpath_CalendarMonthDatesText)
	private List<WebElement> txt_CalendarMonthDates;

	//*******************************************************************
	//***********************Passengers Home Page************************
	//*******************************************************************
	public final String xpath_PassengerTextBox = "//input[@name='passengers']";
	@FindBy(xpath=xpath_PassengerTextBox)
	private WebElement txtbx_Passenger;

	public final String xpath_PassengerTypeText = "//app-passenger-picker-dropdown/div/div/div/div[1]";
	@FindBy(xpath = xpath_PassengerTypeText)
	private List<WebElement> txt_PassengerType;

	public final String xpath_AdultMinusLink = "//div[contains(text(),'Adults') or contains(text(),'Adultos')]//following-sibling::div[1]//i[contains(@class,'icon-minus-circle')]";
	@FindBy(xpath=xpath_AdultMinusLink)
	private WebElement lnk_AdultMinus;

	public final String xpath_AdultCountTextBox= "//div[contains(text(),'Adults') or contains(text(),'Adultos')]//following-sibling::div[1]//div[contains(@class,'counter-number')]/input";
	@FindBy(xpath=xpath_AdultCountTextBox)
	private WebElement txtbx_AdultCount;

	public final String xpath_AdultPlusLink = "//div[contains(text(),'Adults') or contains(text(),'Adultos')]//following-sibling::div[1]//i[contains(@class,'icon-add-circle')]";
	@FindBy(xpath=xpath_AdultPlusLink)
	private WebElement lnk_AdultPlus;

	public final String xpath_ChildMinusLink = "//div[contains(text(),'Children') or contains(text(),'Niños')]/../../div[2]//i[contains(@class,'icon-minus-circle')]";
	@FindBy(xpath=xpath_ChildMinusLink)
	private WebElement lnk_ChildMinus;

	public final String xpath_ChildCountTextBox= "//div[contains(text(),'Children') or contains(text(),'Niños')]/../../div[2]//div[contains(@class,'counter-number')]/input";
	@FindBy(xpath=xpath_ChildCountTextBox)
	private WebElement txtbx_ChildCount;

	public final String xpath_ChildPlusLink = "//div[contains(text(),'Children') or contains(text(),'Niños')]/../../div[2]//i[contains(@class,'icon-add-circle')]";
	@FindBy(xpath=xpath_ChildPlusLink)
	private WebElement lnk_ChildPlus;

	//*******************************************************************
	//*****************************Car Driver****************************
	//*******************************************************************
	public final String xpath_DriversAgeDropDown = "//select[@id='package-driverAge']";
	@FindBy(xpath=xpath_DriversAgeDropDown)
	private WebElement drpdwn_DriversAge;

	//*******************************************************************
	//*******************No Car Available POp Up ************************
	//*******************************************************************
	public final String xpath_NoCarAvailablePopUpHeaderText = "//app-branded-modal//h2";
	@FindBy(xpath=xpath_NoCarAvailablePopUpHeaderText)
	private WebElement txt_NoCarAvailablePopUpHeader;

	public final String xpath_NoCarAvailablePopUpCloseButton = "//app-branded-modal//button[@class='close']";
	@FindBy(xpath=xpath_NoCarAvailablePopUpCloseButton)
	private WebElement btn_NoCarAvailablePopUpClose;

	public final String xpath_NoCarAvailablePopUpInfoText = "//app-branded-modal//p";
	@FindBy(xpath=xpath_NoCarAvailablePopUpInfoText)
	private WebElement txt_NoCarAvailablePopUpInfo;

	public final String xpath_NoCarAvailablePopUpChangeFlightButton = "//app-branded-modal//button[contains(text(),'Change Dates') or contains(text(),'Cambiar Las Fechas')]";
	@FindBy(xpath=xpath_NoCarAvailablePopUpChangeFlightButton)
	private WebElement btn_NoCarAvailablePopUpChangeFlight;

	//*******************************************************************
	//*****************************Hotel Room****************************
	//*******************************************************************
	public final String xpath_RoomsDropDown = "//select[contains(@id,'selectHotelRooms') or contains(@id,'hotelRoomCount')]";
	@FindBy(xpath=xpath_RoomsDropDown)
	private WebElement drpdwn_Rooms;

	//*******************************************************************
	//*****************************Promo Code****************************
	//*******************************************************************
	public final String xpath_PromoCodeLink = "//a[contains (text(),'Add a Promo Code') or contains (text(),' Añadir un Código Promocional')]";
	@FindBy(xpath=xpath_PromoCodeLink)
	private WebElement lnk_PromoCode;

	public final String xpath_PromoCodeTextBox = "//input[@id='promoCode']";
	@FindBy(xpath=xpath_PromoCodeTextBox)
	private WebElement txtbx_PromoCode;

	public final String xpath_OptionalServicesPopoverLink = "//span[@popoverclass='optionalServicesPopover']";
	@FindBy(xpath=xpath_OptionalServicesPopoverLink)
	private WebElement lnk_OptionalServicesPopover;

	public final String xpath_PromoSignUpNowLink = "//ngb-popover-window//a[contains(text(),'Sign Up Now') or contains (text(), 'Inscríbase ahora')]";
	@FindBy(xpath=xpath_PromoSignUpNowLink)
	private WebElement lnk_PromoSignUpNow;

	public final String xpath_PopOverContainerText = "//div[@class='popover-body']/div/div/div";
	@FindBy(xpath=xpath_PopOverContainerText)
	private WebElement txt_PopOverContainer;

	public final String xpath_PopUpOverCloseImage = "//div[@class='popover-body']//a[@class='icon-close popover-circle']";
	@FindBy(xpath = xpath_PopUpOverCloseImage)
	private WebElement img_PopUpOverClose;

	//*******************************************************************
	//************************Promo Code Popup***************************
	//*******************************************************************
	public final String xpath_PromoCodePopupHeaderText = "//h2[contains(text(),'Promotion Code')]";
	@FindBy(xpath=xpath_PromoCodePopupHeaderText)
	private WebElement txt_PromoCodePopupHeader;

	public final String xpath_PromoCodePopupCloseButton = "//div[@class='modal-header']//i[@class='icon-close']";
	@FindBy(xpath=xpath_PromoCodePopupCloseButton)
	private WebElement btn_PromoCodePopupClose;

	public final String xpath_PromoCodePopupVerbiage1Text = "//div[@class='modal-body']//p";
	@FindBy(xpath=xpath_PromoCodePopupVerbiage1Text)
	private List<WebElement> txt_PromoCodePopupVerbiage1;

	public final String xpath_PromoCodePopupVerbiage2Text = "//div[@class='modal-body']//li";
	@FindBy(xpath=xpath_PromoCodePopupVerbiage2Text)
	private List<WebElement> txt_PromoCodePopupVerbiage2;

	public final String xpath_PromoCodePopupEditCouponCodeButton = "//button[contains(text(),'edit coupon code')]";
	@FindBy(xpath=xpath_PromoCodePopupEditCouponCodeButton) //no spanish
	private WebElement btn_PromoCodePopupEditCouponCode;

	public final String xpath_PromoCodePopupContinueWitoutCouponCodeButton = "//button[contains(text(),'continue without coupon code')]";
	@FindBy(xpath=xpath_PromoCodePopupContinueWitoutCouponCodeButton) //no spanish
	private WebElement btn_PromoCodePopupContinueWitoutCouponCode;

	//*******************************************************************
	//*******************OneWay International Popup**********************
	//*******************************************************************
	public final String xpath_OneWayInternationalButton = "//div[@class='popover-body']//button";
	@FindBy(xpath=xpath_OneWayInternationalButton)
	private WebElement btn_OneWayInternational;

	//*******************************************************************
	//*******************Unaccompanied Minor Popup***********************
	//*******************************************************************
	public final String xpath_UMNRAcceptButton = "//button[contains(text(), 'accept') or contains(text(), 'ACEPTAR')]";
	@FindBy(xpath=xpath_UMNRAcceptButton)
	private WebElement btn_UMNRAccept;

	//*******************************************************************
	//**************************Error Message****************************
	//*******************************************************************
	public final String xpath_ErrorMessageText = "//div[contains(@class,'s-error-text')]";
	@FindBy(xpath=xpath_ErrorMessageText)
	private WebElement txt_ErrorMessage;

	//*******************************************************************
	//***********************Child Popup Home Page***********************
	//*******************************************************************

	public final String xpath_ChildTravelerPanel = "//div[@data-qa='child-traveler']";
	@FindBy(xpath=xpath_ChildTravelerPanel)
	private List<WebElement> pnl_ChildTraveler;

	public final String xpath_Age0To17VerbiageText = "//span[contains(text(),'Ages 0-17') or contains(text(),'Edades 0-17')]";
	@FindBy(xpath=xpath_Age0To17VerbiageText)
	private WebElement txt_Age0To17Verbiage;

	public final String xpath_ChildBirthTextBox = "//input[contains(@id,'dateOfBirth')]";
	@FindBy(xpath=xpath_ChildBirthTextBox)
	private List<WebElement> txtbx_ChildBirth;

	public final String xpath_ChildPopUpButton = "//button[contains(text(),'continue') or contains(text(),'Continuar')]";
	@FindBy(xpath=xpath_ChildPopUpButton)
	private WebElement btn_ChildPopUp;

	//*******************************************************************
	//***********************Young Travelers Popup***********************
	//*******************************************************************
//	public final String xpath_YoungTravelerPopupPanel = "//app-young-travelers-modal";
	public final String xpath_YoungTravelerPopupPanel = "//app-branded-modal";
	@FindBy(xpath=xpath_YoungTravelerPopupPanel)
	private WebElement YoungTravelerPopup;

	public final String xpath_YoungTravelerPopupHeaderText = "//app-young-travelers-modal//h2";
	@FindBy(xpath=xpath_YoungTravelerPopupHeaderText)
	private WebElement txt_YoungTravelerPopupHeader;

	public final String xpath_YoungTravelerPopupText = "//app-young-travelers-modal//p";
	@FindBy(xpath=xpath_YoungTravelerPopupText)
	private List<WebElement> txt_YoungTravelerPopup;

	public final String xpath_YoungTravelerPopupCloseButton = "//app-young-travelers-modal//button[contains(text(),'CLOSE') or contains(text(),'Cerrar')]";
	@FindBy(xpath=xpath_YoungTravelerPopupCloseButton)
	private WebElement btn_YoungTravelerPopupClose;

	//*******************************************************************
	//*********Passengers Required Popup Home Page***********************
	//*******************************************************************
	public final String xpath_PassengersRequiredHeaderText = "//div[@class='modal-header']//h2[contains (text(),'Passengers Required') or contains (text(),'Se Requieren Pasajeros')]";
	@FindBy(xpath=xpath_PassengersRequiredHeaderText)
	private WebElement txt_PassengersRequiredHeader;

	public final String xpath_PassengersRequiredCloseText = "//div[@class='modal-content']//button[contains(text(),'Close Window') or contains(text(),'Cerrar la Ventana')]";
	@FindBy(xpath=xpath_PassengersRequiredCloseText)
	private WebElement txt_PassengersRequiredClose;

	//*******************************************************************
	//************Seasonal Service Popup Home Page***********************
	//*******************************************************************
	public final String xpath_SeasonalServiceText = "//div[@class='modal-body']//p";
	@FindBy(xpath=xpath_SeasonalServiceText)
	private WebElement txt_SeasonalService;

	public final String xpath_SeasonalServicePopUpCloseButton = "//app-branded-modal//button[@class='close']";
	@FindBy(xpath=xpath_SeasonalServicePopUpCloseButton)
	private WebElement btn_SeasonalServicePopUpClose;

	public final String xpath_SeasonalServicePopUpCloseWindowButton = "//div[@class='modal-content']//button[contains(text(),'Close Window') or contains(text(),'Cerrar la Ventana')]";
	@FindBy(xpath= xpath_SeasonalServicePopUpCloseWindowButton)
	private WebElement btn_SeasonalServicePopUpCloseWindow;

	//*******************************************************************
	//***********************Search Button Home Page*********************
	//*******************************************************************
	public final String xpath_WhereWeFlyLink = "//i[@class='icon-where-we-fly']";
	@FindBy(xpath=xpath_WhereWeFlyLink)
	private WebElement lnk_WhereWeFly;

	public final String xpath_SearchFlightButton = "//button[contains(text(),'Search Flights') or contains(text(),'Buscar Vuelos')]";
	@FindBy(xpath=xpath_SearchFlightButton)
	private List<WebElement> btn_SearchFlight;

	public final String xpath_SearchVacationButton = "//button[contains(text(),'Search Vacation') or contains(text(),'Buscar Vacaciones')]";
	@FindBy(xpath=xpath_SearchVacationButton)
	private List<WebElement> btn_SearchVacation;

	public final String xpath_SearchCarButton = "//button[contains(text(),'Search Car') or contains(text(),'Buscar Auto')]";
	@FindBy(xpath=xpath_SearchCarButton)
	private List<WebElement> btn_SearchCar;

	//*******************************************************************
	//**************************My Trips Tab****************************
	//*******************************************************************

	//guest
	public final String id_MyTripsLastNameTextBox = "my-trips-lastName";
	@FindBy(id=id_MyTripsLastNameTextBox)
	private WebElement txtbx_MyTripsLastName;

	public final String id_MyTripsPNRTextBox = "my-trips-recordLocator";
	@FindBy(id=id_MyTripsPNRTextBox)
	private WebElement txtbx_MyTripsPNR;

	public final String xpath_MyTripsSearchButton = "//button[contains(text(),'continue') or contains(text(),'continuar')]";
	@FindBy(xpath=xpath_MyTripsSearchButton)
	private WebElement btn_MyTripsSearch;

	//logged in member reservations table *********all these elements need attributes**********
	//route

	public final String xpath_ManageTravelVerbageText = "//app-manage-travel-home//p[contains(text(),'Change or cancel')]";
	@FindBy(xpath = xpath_ManageTravelVerbageText)
	private WebElement txt_ManageTravelVerbage;

	public final String xpath_ManageTravelConfirmationCodeLink = "(//a[contains(text(),' Confirmation Code ') or contains(text(),' Clave de Confirmación ')])[1]";
	@FindBy(xpath = xpath_ManageTravelConfirmationCodeLink)
	private WebElement lnk_ManageTravelConfirmationCode;

	public final String xpath_ManageTravelRouteText = "(//div[@class = 'card-body']/div//strong[text()='Route' or text()='Ruta'])[1]";
	@FindBy(xpath = xpath_ManageTravelRouteText)
	private WebElement txt_ManageTravelRoute;

	public final String xpath_ManageTravelDateText = "(//div[@class = 'card-body']/div//strong[text()='Date' or text()='Fecha'])[1]";
	@FindBy(xpath = xpath_ManageTravelDateText)
	private WebElement txt_ManageTravelDate;

	public final String xpath_ManageTravelConfirmationCodeText = "(//div[@class = 'card-body']/div//strong[text()='Confirmation Code' or text()='Clave de Confirmación'])[1]";
	@FindBy(xpath = xpath_ManageTravelConfirmationCodeText)
	private WebElement txt_ManageTravelConfirmationCode;

	public final String xpath_ManageTravelTableRouteText = "//div[contains(@class,'items-baseline')]//p[contains(text(),'-')]";
	@FindBy(xpath=xpath_ManageTravelTableRouteText)
	private List<WebElement> txt_ManageTravelTableRoute;

	//date of travel
	public final String xpath_ManageTravelTableDateText = "//div[contains(@class,'items-baseline')]//p[contains(text(),'2019') or contains(text(),'2020')]";
	@FindBy(xpath=xpath_ManageTravelTableDateText)
	private List<WebElement> txt_ManageTravelTableDate;

	//Confirmation Code
	public final String xpath_ManageTravelTableConfirmationCodeText = "//div[contains(@class,'items-baseline')]//div[3]//p";
	@FindBy(xpath=xpath_ManageTravelTableConfirmationCodeText)
	private List<WebElement> txt_ManageTravelTableConfirmationCode;

	//Continue Button
	public final String xpath_ManageTravelTableContinueButton = "//div[contains(@class,'items-baseline')]//button";
	@FindBy(xpath=xpath_ManageTravelTableContinueButton)
	private List<WebElement> btn_ManageTravelTableContinue;

	//show all
	public final String xpath_ManageTravelShowAllButton = "//button[contains(text(),'Show All') or contains(text(),'Monstrar Todos')]";
	@FindBy(xpath=xpath_ManageTravelShowAllButton)
	private WebElement btn_ManageTravelShowAll;

	//use another Confirmation Code
	public final String xpath_ManageTravelAnotherConfirmationCodeButton = "//a[contains(text(),'Use another Confirmation Code') or contains(text(),'Usar otra Clave de Confirmación')]";
	@FindBy(xpath=xpath_ManageTravelAnotherConfirmationCodeButton)
	private WebElement btn_ManageTravelAnotherConfirmationCode;

	//*******************************************************************
	//***************My Trips Tab Your Confirmation Page Popup***********
	//*******************************************************************

	public final String xpath_ManageTravelConfirmationCodePopUpHeaderText = "//h2[@class='modal-title']";
	@FindBy(xpath = xpath_ManageTravelConfirmationCodePopUpHeaderText)
	private WebElement txt_ManageTravelConfirmationCodePopUpHeader;

	public final String xpath_ManageTravelConfirmationCodePopUpCrossButton = "//div[@class='modal-header']/button[@class='close']/span";
	@FindBy(xpath = xpath_ManageTravelConfirmationCodePopUpCrossButton)
	private WebElement btn_ManageTravelConfirmationCodePopUpCross;

	public final String xpath_ManageTravelConfirmationCodePopupCloseWindowButton = "//button[contains(text(),'CLOSE WINDOW') or contains(text(),'CERRAR VENTANA')]";
	@FindBy(xpath = xpath_ManageTravelConfirmationCodePopupCloseWindowButton)
	private WebElement btn_ManageTravelConfirmationCodePopupCloseWindow;

	//*******************************************************************
	//**************************Lap Child Popup**************************
	//*******************************************************************
	public final String xpath_LapChildPopupHeaderText = "//div[@class='modal-header']//h2";
	@FindBy(xpath=xpath_LapChildPopupHeaderText)
	private WebElement txt_LapChildPopupHeader;

	public final String xpath_LapChildPopUpXButton = "//div[@class='modal-header']//button";
	@FindBy(xpath=xpath_LapChildPopUpXButton)
	private WebElement btn_LapChildPopUpX;

	public final String xpath_LapChildPopUpInfoText = "//div[@class='modal-body']//p";
	@FindBy(xpath=xpath_LapChildPopUpInfoText)
	private WebElement txt_LapChildPopUpInfo;

	public final String xpath_LapChildPopUpCloseButton = "//div[@class='modal-body']//button";
	@FindBy(xpath=xpath_LapChildPopUpCloseButton)
	private WebElement btn_LapChildPopUpClose;

	//*******************************************************************
	//**************************Get Update Popup*************************
	//*******************************************************************
	public final String xpath_GetUpdatePopupHeaderText = "//div[@class='modal-header']/h2";
	@FindBy(xpath=xpath_GetUpdatePopupHeaderText)
	private WebElement txt_GetUpdatePopupHeader;

	public final String xpath_GetUpdatePopupCloseLink = "//div[@class='modal-header']//button";
	@FindBy(xpath=xpath_GetUpdatePopupCloseLink)
	private WebElement lnk_GetUpdatePopupClose;

	public final String xpath_GetUpdatePopupVerbiageText = "//div[@class='modal-body']//p";
	@FindBy(xpath=xpath_GetUpdatePopupVerbiageText)
	private WebElement txt_GetUpdatePopupVerbiage;

	//*******************************************************************
	//**************************Marketing Tiles**************************
	//*******************************************************************
	public final String xpath_JoinAndSavePanel = "//div[contains(@class,'marketing-tiles-margin')]/div[1]";
	@FindBy(xpath=xpath_JoinAndSavePanel)
	private WebElement pnl_JoinAndSave;

	public final String xpath_SubscribeAndSavePanel = "//div[contains(@class,'marketing-tiles-margin')]/div[2]";
	@FindBy(xpath=xpath_SubscribeAndSavePanel)
	private WebElement pnl_SubscribeAndSave;

	public final String xpath_LimitedTimeOfferPanel = "//div[contains(@class,'marketing-tiles-margin')]/div[3]";
	@FindBy(xpath=xpath_LimitedTimeOfferPanel)
	private WebElement pnl_LimitedTimeOffer;

	//*******************************************************************
	//***********************Trip Planing Home Page**********************
	//*******************************************************************
	public final String xpath_TripPlanningLink = "//div[@id='em_trip_planning']//h2";
	@FindBy(xpath=xpath_TripPlanningLink)
	private WebElement lnk_TripPlanning;

	public final String xpath_TripPlanningInfoText = "//ul[@class='cities']//li";
	@FindBy(xpath=xpath_TripPlanningInfoText)
	private List<WebElement> txt_TripPlanningInfo;

	public final String xpath_TripPlanningHeaderText = "//div[@class='headline4']";
	@FindBy(xpath=xpath_TripPlanningHeaderText)
	private List<WebElement> txt_TripPlanningHeader;

	public final String xpath_TripPlanningHeaderInfoText = "//div[@class='headline4']//following-sibling::div";
	@FindBy(xpath=xpath_TripPlanningHeaderInfoText)
	private List<WebElement> txt_TripPlanningHeaderInfo;


	//*****************************************************************************************************************
	//*************************************Start of Methods of Home Page***********************************************
	//*****************************************************************************************************************
	//*******************************************************************
	//*******************Top Left Header Home Page**********************
	//*******************************************************************
	public WebElement getSpiritLogoImage() {
		return img_SpiritLogo;
	}

	public WebElement getOptionalServiceLink() {
		return lnk_OptionalService;
	}

	//*******************************************************************
	//*******************Top Right Header Home Page**********************
	//*******************************************************************
	public List<WebElement> getSignInListLink() {
		return lnk_SignInList;
	}

	public List<WebElement> getLoginUserIconImage(){
		return Img_Usericon;
	}

	public WebElement getIconBar(){
		return img_IconBar;
	}

	public List<WebElement> getSelectedLanguage(){
		return lnk_SelectedLanguage;
	}

	public List<WebElement> get_HelpListLink() {return lnk_HelpList;}

	public List<WebElement> get_ContactUsListLink() {return lnk_ContactUsList;}

	public List<WebElement> get_DealsListLink() {return lnk_DealsList;}

	public List<WebElement> get_$9FareClubListLink(){return lnk_$9FareClubList;}

	public List<WebElement> get_Spirit101ListLink() {return lnk_Spirit101List;}

	public List<WebElement> get_DestinationsListLink() {return lnk_DestinationsList;}

	//*******************************************************************
	//*******************TAB List Home Page******************************
	//*******************************************************************
	public WebElement getSearchWidgetPanel() {
		return pnl_SearchWidget;
	}

	public WebElement getBookPathLink() {
		for(WebElement bookPathLink : lnk_BookPath){
			if(bookPathLink.isDisplayed()){
				return bookPathLink;
			}
		}
		return null;
	}

	public WebElement getMyTripPathLink() {
		for(WebElement myTripPathLink : lnk_MyTripPath){
			if(myTripPathLink.isDisplayed()){
				return myTripPathLink;
			}
		}
		return null;
	}

	public WebElement getCheckInPathLink() {
		for(WebElement checkInPathLink : lnk_CheckInPath){
			if(checkInPathLink.isDisplayed()){
				return checkInPathLink;
			}
		}
		return null;
	}

	public WebElement getFlightStatusPathLink() {
		for(WebElement flightStatusPathLink : lnk_FlightStatusPath){
			if(flightStatusPathLink.isDisplayed()){
				return flightStatusPathLink;
			}
		}
		return null;
	}

	//*******************************************************************
	//*******************Trip Tab Home Page******************************
	//*******************************************************************
	public WebElement getMyTripConfirmationCodeLink(){
		return lnk_MyTripConfirmationCode;
	}

	public WebElement getMyTripConfirmationCodeChevronLink(){
		return lnk_MyTripConfirmationCodeChevron;
	}

	public WebElement getMyTripConfirmationCodeText(){
		return txt_MyTripConfirmationCode;
	}

	public WebElement getMyTripLastNameTextBox() {
		return txtbx_MyTripLastName;
	}

	public WebElement getMyTripConfirmationCodeTextBox() {
		return txtbx_MyTripConfirmationCode;
	}

	public WebElement getMyTripContinueButton() {
		return btn_MyTripContinue;
	}

	//*******************************************************************
	//*******************CheckIn Tab Home Page***************************
	//*******************************************************************
	public WebElement getCheckInLastNameTextBox() {
		return txtbx_CheckInLastName;
	}

	public WebElement getCheckInConfirmationCodeTextBox() {
		return txtbx_CheckInConfirmationCode;
	}

	public WebElement getWhereToFindYourConfirmationCodeLink() {
		return lnk_WhereToFindYourConfirmationCode;
	}

	public WebElement getCheckInButton() {
		return btn_CheckIn;
	}

	public WebElement getReservationNotFoundHeaderTxt() { return txt_ReservationNotFoundHeader; }

	public WebElement getReservationNotFoundBodyTxt() { return txt_ReservationNotFoundBody; }

	public WebElement getReservationNotFoundCloseBtn() { return btn_ReservationNotFoundClose; }

	//*******************************************************************
	//*******************FlightStatus Tab Home Page**********************
	//*******************************************************************
	public WebElement getCheckByDestinationLabel() {
		return lbl_CheckByDestination;
	}

	public WebElement getCheckByFlightNumberLabel() {
		return lbl_CheckByFlightNumber;
	}

	public WebElement getFlightStatusSubHeaderText() {
		return txt_FlightStatusSubHeader;
	}


	public WebElement getFlightStatusFlightNumberTextBox() {
		return txtbx_FlightStatusFlightNumber;
	}

	public WebElement getFlightStatusFlightNumberImage() {
		return img_FlightStatusFlightNumber;
	}


	public WebElement getFlightStatusDateDropDown() {
		return drpdwn_FlightStatusDate;
	}

	public WebElement getFlightStatusDateImage() {
		return img_FlightStatusDate;
	}

	public WebElement getFlightStatusCheckStatusButton() {
		return btn_FlightStatusCheckStatus;
	}

	public WebElement getFlightStatusStationAdvisoryText() {
		return txt_FlightStatusStationAdvisory;
	}

	public WebElement getFlightStatusStationAdvisoryLearnMoreLink() {
		return lnk_FlightStatusStationAdvisoryLearnMore;
	}

	public WebElement getFlightStatusDateText() {
		return txt_FlightStatusDate;
	}

	public List<WebElement> getFLightStatusFlightNumberText() {
		return txt_FLightStatusFlightNumber;
	}

	public List<WebElement> getFlightStatusOnTimeText() {
		return txt_FlightStatusOnTime;
	}

	public List<WebElement> getFlightStatusGetUpdateButton() {
		return btn_FlightStatusGetUpdate;
	}

	public List<WebElement> getGetUpdateHeaderText() {
		return txt_GetUpdateHeader;
	}

	public List<WebElement> getGetUpdateEmailLabel() {
		return lbl_GetUpdateEmail;
	}

	public List<WebElement> getGetUpdateEmailTextBox() {
		return txtbx_GetUpdateEmail;
	}

	public List<WebElement> getGetUpdateCancelButton() {
		return btn_GetUpdateCancel;
	}

	public List<WebElement> getGetUpdateGetUpdateButton() {
		return btn_GetUpdateGetUpdate;
	}

	public List<WebElement> getFlightStatusCollapseShowLink() {
		return lnk_FlightStatusCollapseShow;
	}

	public List<WebElement> getFlightStatusCollapseShowDepartureText() {
		return txt_FlightStatusCollapseShowDeparture;
	}

	public List<WebElement> getFlightStatusCollapseShowArrivalText() {
		return txt_FlightStatusCollapseShowArrival;
	}

	public List<WebElement> getFlightStatusCollapseShowTimeText() {
		return txt_FlightStatusCollapseShowTime;
	}

	public WebElement getFlightStatusSelectedDepartureAirportText() {
		return txt_FlightStatusSelectedDepartureAirport;
	}

	public WebElement getFlightStatusSelectedArrivalAirportText() {
		return txt_FlightStatusSelectedArrivalAirport;
	}

	//***********************************************************
	//*******************your Confirmation Code Popup************
	//***********************************************************
	public WebElement getCheckInHowToFindConfirmationCodeLink(){
		return lnk_CheckInHowToFindConfirmationCode;
	}

	public WebElement getPopUpCrossButton(){
		return btn_PopUpCrossButton;
	}

	public WebElement getYouConfirmationPopupHeaderText(){
		return txt_YouConfirmationPopupHeader;
	}

	public WebElement getYouConfirmationPopupImage(){
		return img_YouConfirmationPopupImage;
	}

	public WebElement getExpediaConfirmationPopUpLink(){
		return lnk_ExpediaConfirmationPopUp;
	}

	public WebElement getPricelineConfirmationPopUpLink(){
		return lnk_PricelineConfirmationPopUp;
	}

	public WebElement getCheapoairConfirmationPopUpLink(){
		return lnk_CheapoairConfirmationPopUp;
	}

	public WebElement getOrbitzConfirmationPopUpLink(){
		return lnk_OrbitzConfirmationPopUp;
	}

	public WebElement getSpiritConfirmationPopUpLink(){
		return lnk_SpiritConfirmationPopUp;
	}

	//*******************************************************************
	//*******************Login Popup Home Page***************************
	//*******************************************************************
	public WebElement getUserNameHeaderText() {
		return txt_UserNameHeader;
	}

	public WebElement getUserNameBox() {
		return txtbx_UserName;
	}

	public WebElement getPasswordHeaderText() {
		return txt_PasswordHeader;
	}

	public WebElement getPasswordBox() {
		return txtbx_Password;
	}

	public WebElement getResetPasswordButton() {
		return btn_ResetPassword;
	}

	public WebElement getLoginButton() {
		return btn_Login;
	}

	public WebElement getSignUpNowLink() {
		return lnk_SignUpNow;
	}

	public WebElement getNewPasswordLabel() { return txt_NewPassword; }

	public WebElement getNewPasswordBox() { return txtbx_NewPassword; }

	public WebElement getConfirmNewPasswordLabel() { return txt_ConfirmNewPassword; }

	public WebElement getConfirmNewPasswordBox() { return txtbx_ConfirmNewPassword; }

	public WebElement getLoginPopUpCloseButton(){
		return btn_LoginPopUpClose;
	}

	//*******************************************************************
	//*******************Journey Type Home Page**************************
	//*******************************************************************
	public WebElement getFlightBookingLink() {
		return lnk_FlightBooking;
	}

	public WebElement getVacationBookingLink() {
		return lnk_VacationBooking;
	}

	public WebElement getCarBookingLink() {
		return lnk_CarBooking;
	}

	public WebElement getHotelBookingLink() {
		return lnk_HotelBooking;
	}

	public WebElement getCruiseBookingLink() {
		return lnk_CruiseBooking;
	}

	//*******************************************************************
	//*********************Trip Type Home Page***************************
	//*******************************************************************
	public WebElement getRoundTripRadioButton() {
		return rdbtn_RoundTrip;
	}

	public WebElement getRoundTripLabel() {
		return lbl_RoundTrip;
	}

	public WebElement getOneWayRadioButton() {
		return rdbtn_OneWay;
	}

	public WebElement getOneWayLabel() {
		return lbl_OneWay;
	}

	public WebElement getMultiCityRadioButton() {
		return rdbtn_MultiCity;
	}

	public WebElement getMultiCityLabel() {
		return lbl_MultiCity;
	}

	//*******************************************************************
	//*********************Dollarss or Miles Home Page*******************
	//*******************************************************************

	public WebElement getMilesLabel(){
		return lbl_Miles;
	}

	//*******************************************************************
	//*********************Vacation Type Home Page***********************
	//*******************************************************************
	public WebElement getFlightCarRadioButton() {
		return rdbtn_FlightCar;
	}

	public WebElement getFlightCarLabel() {
		return lbl_FlightCar;
	}

	public WebElement getFlightHotelRadiobutton() {
		return rdbtn_FlightHotel;
	}

	public WebElement getFlightHotelLabel() {
		return lbl_FlightHotel;
	}

	public WebElement getFlightHotelCarRadiobutton() {
		return rdbtn_FlightHotelCar;
	}

	public WebElement getFlightHotelCarLabel() {
		return lbl_FlightHotelCar;
	}

	//*******************************************************************
	//***********************Airport Home Page***************************
	//*******************************************************************
	public List<WebElement> getAllLocationAirportText() {
		return txt_AllLocationAirport;
	}

	public List<WebElement> getNorthAmericaAirportText() {
		return txt_NorthAmericaAirport;
	}

	public List<WebElement> getCentralAmericaAirportText() {
		return txt_CentralAmericaAirport;
	}

	public List<WebElement> getSouthAmericaAirportText() {
		return txt_SouthAmericaAirport;
	}

	public List<WebElement> getCaribbeanAirportText() {
		return txt_Caribbean;
	}

	public List<WebElement> getDepartAirportBox() {
		return txtbx_DepartAirport;
	}

	public List<WebElement> getMultiCityDepartAirportBox() {
		return txtbx_MultiCityDepartAirport;
	}

	public List<WebElement> getArrivalAirportBox() {
		return txtbx_ArrivalAirport;
	}

	public List<WebElement> getMultiCityArrivalAirportBox() {
		return txtbx_MultiCityArrivalAirport;
	}

	public List<WebElement> getAirportListText() {
		return txt_AirportList;
	}

	public List<WebElement> getStationCloseButton() {
		return btn_StationClose;
	}

	public WebElement getultiCityAddAnotherFlighteButton() {
		return btn_MultiCityAddAnotherFlight;
	}

	public WebElement getFromLabel(){
		return lbl_From;
	}

	public WebElement getFromArrowDownImage(){
		return img_FromArrowDown;
	}

	public WebElement getRoundTripArrowsImage(){
		return img_RoundTripArrows;
	}

	//*******************************************************************
	//*************************Date Home Page****************************
	//*******************************************************************
	public WebElement getDateBox() {
		return txtbx_Date;
	}

	public List<WebElement>  getMultiCityDateBox() {
		return txtbx_MultiCityDate;
	}

	public List<WebElement> getCalenderHeaderText() {
		return txt_CalenderHeader;
	}

	public List<WebElement> getCalendarPreviousButton(){
		return btn_PreviousMonth;
	}

	public List<WebElement> getCalendarNextButton(){
		return btn_NextMonth;
	}

	public List<WebElement> getCalenderPanel(){
		return pnl_Calender;
	}

	public List<WebElement> getCalendarHeaderValuesText(){
		return txt_CalendarHeaderValues;
	}

	public List<WebElement> getCalendarMonthDatesText(){
		return txt_CalendarMonthDates;
	}
	//*******************************************************************
	//***********************Passengers Home Page************************
	//*******************************************************************
	public WebElement getPassengerBox() {
		return txtbx_Passenger;
	}

	public List<WebElement> getPassengerTypeText(){
		return txt_PassengerType;
	}

	public WebElement getAdultMinusLink() {
		return lnk_AdultMinus;
	}

	public WebElement getAdultBox() {
		return txtbx_AdultCount;
	}

	public WebElement getAdultPlusLink() {
		return lnk_AdultPlus;
	}

	public WebElement getChildMinusLink() {
		return lnk_ChildMinus;
	}

	public WebElement getChildBox() {
		return txtbx_ChildCount;
	}

	public WebElement getChildPlusLink() {
		return lnk_ChildPlus;
	}

	//*******************************************************************
	//*****************************Car Driver****************************
	//*******************************************************************
	public WebElement getDriversAgeDropDown() {
		return drpdwn_DriversAge;
	}

	//*******************************************************************
	//*****************No Car Available Pop Up Methid********************
	//*******************************************************************

	public WebElement getNoCarAvailablePopUpHeaderText() {return txt_NoCarAvailablePopUpHeader;}

	public WebElement getNoCarAvailablePopUpCloseButton() {return btn_NoCarAvailablePopUpClose;}

	public WebElement getNoCarAvailablePopUpInfoText() {return txt_NoCarAvailablePopUpInfo;}

	public WebElement getNoCarAvailablePopUpChangeFlightButton() {return btn_NoCarAvailablePopUpChangeFlight;}

	//*******************************************************************
	//*****************************Hotel Room****************************
	//*******************************************************************
	public WebElement getRoomsDropDown() {
		return drpdwn_Rooms;
	}

	//*******************************************************************
	//*****************************Promo Code****************************
	//*******************************************************************
	public WebElement getPromoCodeLink() {
		return lnk_PromoCode;
	}

	public WebElement getPromoCodeTextBox() {
		return txtbx_PromoCode;
	}

	public WebElement getOptionalServicesPopoverLink() {
		return lnk_OptionalServicesPopover;
	}

	public WebElement getPromoSignUpNowLink() {
		return lnk_PromoSignUpNow;
	}

	public WebElement getPopOverContainerText() {
		return txt_PopOverContainer;
	}

	public WebElement getPopUpOverCloseImage(){
		return img_PopUpOverClose;
	}

	//*******************************************************************
	//************************Promo Code Popup***************************
	//*******************************************************************
	public WebElement getPromoCodePopupHeaderText() {
		return txt_PromoCodePopupHeader;
	}

	public WebElement getPromoCodePopupCloseButton() {
		return btn_PromoCodePopupClose;
	}

	public List<WebElement> getPromoCodePopupVerbiage1Text() {
		return txt_PromoCodePopupVerbiage1;
	}

	public List<WebElement> getPromoCodePopupVerbiage2Text() {
		return txt_PromoCodePopupVerbiage2;
	}

	public WebElement getPromoCodePopupEditCouponCodeButton() {
		return btn_PromoCodePopupEditCouponCode;
	}

	public WebElement getPromoCodePopupContinueWitoutCouponCodeButton() {
		return btn_PromoCodePopupContinueWitoutCouponCode;
	}

	//*******************************************************************
	//*******************OneWay International Popup**********************
	//*******************************************************************
	public WebElement getOneWayInternationalButton() {
		return btn_OneWayInternational;
	}

	//*******************************************************************
	//*******************Unaccompanied Minor Popup***********************
	//*******************************************************************
	public WebElement getUMNRAcceptButton() {
		return btn_UMNRAccept;
	}

	//*******************************************************************
	//**************************Error Message****************************
	//*******************************************************************
	public WebElement getErrorMessageText() {
		return txt_ErrorMessage;
	}

	//*******************************************************************
	//*********Passengers Required Popup Home Page***********************
	//*******************************************************************
	public WebElement getPassengersRequiredHeaderText() {
		return txt_PassengersRequiredHeader;
	}

	public WebElement getPassengersRequiredCloseText() {
		return txt_PassengersRequiredClose;
	}

	//*******************************************************************
	//************Seasonal Service Popup Home Page***********************
	//*******************************************************************
	public WebElement getSeasonalServiceText() {
		return txt_SeasonalService;
	}

	public WebElement getSeasonalServiceCloseButton() {
		return btn_SeasonalServicePopUpClose;
	}

	public WebElement getSeasonalServiceCloseWindowButton() {
		return btn_SeasonalServicePopUpCloseWindow;
	}

	//*******************************************************************
	//***********************Child Popup Home Page***********************
	//*******************************************************************
	public List<WebElement> getChildTravelerPanel(){
		return pnl_ChildTraveler;
	}

	public WebElement getAge0To17Verbiage(){
		return txt_Age0To17Verbiage;
	}

	public List<WebElement> getChildPopUpBirthBoxes() {
		return txtbx_ChildBirth;
	}

	public WebElement getChildPopUpCloseButton() {
		return btn_ChildPopUp;
	}

	//*******************************************************************
	//***********************Young Travelers Popup***********************
	//*******************************************************************

	public WebElement getYoungTravelerPopup() { return YoungTravelerPopup; }

	public WebElement getYoungTravelerPopupHeaderText() { return txt_YoungTravelerPopupHeader; }

	public List<WebElement> getYoungTravelerPopupText() { return txt_YoungTravelerPopup; }

	public WebElement getYoungTravelerPopupCloseButton() { return btn_YoungTravelerPopupClose; }

	//*******************************************************************
	//***********************Search Button Home Page*********************
	//*******************************************************************
	public WebElement getWhereWeFlyLink() {
		return lnk_WhereWeFly;
	}

	public List<WebElement> getSearchFlightButton() {
		return btn_SearchFlight;
	}

	public List<WebElement> getSearchVacationButton() {
		return btn_SearchVacation;
	}

	public List<WebElement> getSearchCarButton() {
		return btn_SearchCar;
	}

	//*******************************************************************
	//***********************My Trips Home Page*********************
	//*******************************************************************
	public WebElement getMyTripsLastNameTextBox() {
		return txtbx_MyTripsLastName;
	}

	public WebElement getMyTripsPNRTextBox() {
		return txtbx_MyTripsPNR;
	}

	public WebElement getMyTripsSearchButton() {
		return btn_MyTripsSearch;
	}

	public WebElement getManageTravelVerbageText(){
		return txt_ManageTravelVerbage;
	}

	public WebElement getManageTravelConfirmationCodeLink(){
		return lnk_ManageTravelConfirmationCode;
	}

	public WebElement getManageTravelRouteText(){
		return txt_ManageTravelRoute;
	}

	public WebElement getManageTravelDateText(){
		return txt_ManageTravelDate;
	}

	public WebElement getManageTravelConfirmationCodeText(){
		return txt_ManageTravelConfirmationCode;
	}


	public List<WebElement> getManageTravelTableRouteTextBox() {
		return txt_ManageTravelTableRoute;
	}

	public List<WebElement> getManageTravelTableDateText() {
		return txt_ManageTravelTableDate;
	}

	public List<WebElement> getManageTravelTableConfirmationCodeText() {
		return txt_ManageTravelTableConfirmationCode;
	}

	public List<WebElement> getManageTravelTableContinueButton() {
		return btn_ManageTravelTableContinue;
	}

	public WebElement getManageTravelShowAllButton() {
		return btn_ManageTravelShowAll;
	}

	public WebElement getManageTravelAnotherConfirmationCodeButton() {
		return btn_ManageTravelAnotherConfirmationCode;
	}


	//*******************************************************************
	//********My Trips Tab Your Confirmation Page Popup Method***********
	//*******************************************************************

	public WebElement getManageTravelConfirmationCodePopUpHeaderText(){
		return txt_ManageTravelConfirmationCodePopUpHeader;
	}

	public WebElement getManageTravelConfirmationCodePopUpCrossButton(){
		return btn_ManageTravelConfirmationCodePopUpCross;
	}

	public WebElement getManageTravelConfirmationCodePopupCloseWindowButton(){
		return btn_ManageTravelConfirmationCodePopupCloseWindow;
	}

	//*******************************************************************
	//**************************Lap Child Popup**************************
	//*******************************************************************
	public WebElement getLapChildPopupHeaderText() { return txt_LapChildPopupHeader; }

	public WebElement getLapChildPopUpXButton() { return btn_LapChildPopUpX; }

	public WebElement getLapChildPopUpInfoText() { return txt_LapChildPopUpInfo; }

	public WebElement getLapChildPopUpCloseButton() { return btn_LapChildPopUpClose; }

	//*******************************************************************
	//**************************Get Update Popup*************************
	//*******************************************************************
	public WebElement getGetUpdatePopupHeaderText(){
		return txt_GetUpdatePopupHeader;
	}

	public WebElement getGetUpdatePopupCloseLink(){
		return lnk_GetUpdatePopupClose;
	}

	public WebElement getGetUpdatePopupVerbiageText(){
		return txt_GetUpdatePopupVerbiage;
	}


	//*******************************************************************
	//**************************Marketing Tiles**************************
	//*******************************************************************
	public WebElement getJoinAndSavePanel() {
		return pnl_JoinAndSave;
	}

	public WebElement getSubscribeAndSavePanel() {
		return pnl_SubscribeAndSave;
	}

	public WebElement getLimitedTimeOfferPanel() {
		return pnl_LimitedTimeOffer;
	}

	//*******************************************************************
	//***********************Trip Planing Home Page**********************
	//*******************************************************************
	public WebElement getTripPlanningLink() { return lnk_TripPlanning; }

	public List<WebElement> getTripPlanningInfoText() { return txt_TripPlanningInfo; }

	public List<WebElement> getTripPlanningHeaderText() { return txt_TripPlanningHeader; }

	public List<WebElement> getTripPlanningHeaderInfoText() { return txt_TripPlanningHeaderInfo; }

}