package com.spirit.WilburBAT;

import com.spirit.baseClass.*;
import com.spirit.dataProviders.*;
import com.spirit.enums.*;
import com.spirit.utility.*;
import org.testng.*;
import org.testng.annotations.*;
import java.util.*;

public class WilburSelectBidOption extends BaseClass {

    @Parameters({"platform"})
    @Test(dataProviderClass = DataGenerator.class, dataProvider = "dp")

    public void WilburSelectBidOption(Hashtable<String,String> data){

        if(!data.get("Runmode").equals("Y")){
            throw new SkipException("Skipping the test case as the Run mode for data set is NO");
        }

        getExtText().pass("Selecting Bid for Test Case ID "+ data.get("TestID") +" "+ data.get("Test_Case_Name"));

        String platform = "Na";

        openBrowser(platform); //Open browser. This creates a new instance of Context which we can use to store the PNR generated by the API
        pageMethodManager.getHomePageMethods().launchSpiritApp();

        //Start check in process using last name and PNR
        scenarioContext.setContext(Context.CONFIRMATION_LASTNAME,  data.get("LastName")); //Store Last Name from Reservation
        scenarioContext.setContext(Context.CONFIRMATION_CODE, data.get("PNR"));

        pageMethodManager.getHomePageMethods().loginToCheckIn();

        WaitUtil.untilPageLoadComplete(getDriver());

        pageMethodManager.getReservationSummaryPageMethods().clickCheckInAndGetBoardingPass();

        //Validate the pop-up
        pageMethodManager.getReservationSummaryPageMethods().validateSolicitVolunteerText(String.valueOf(((int) Double.parseDouble(data.get("Tier")))));

        //get the bid option
        String  bidOption= data.get("BID");
        if (bidOption.equals("Bid5"))//If bidOption "Bid5", concatenate the bid amount
        {
            bidOption = bidOption + (data.get("AMOUNT"));
        }

        System.out.println(bidOption);

        pageMethodManager.getReservationSummaryPageMethods().selectBidOption(bidOption);
        pageMethodManager.getReservationSummaryPageMethods().submitBid();

        WaitUtil.untilPageLoadComplete(getDriver());
        pageObjectManager.getReservationSummaryPage().getBidAcceptedCloseButton().click();

        WaitUtil.untilTimeCompleted(1000);
        WaitUtil.untilPageLoadComplete(getDriver());


    }
}
