package com.spirit.enums;

public enum Context {
	//Home Page Global variable
	HOMEPAGE_BROWSER,
	HOMEPAGE_MOBILE,
	HOMEPAGE_LANGUAGE,
	HOMEPAGE_CITYPAIRS,
	HOMEPAGE_LOGINTYPE,
	HOMEPAGE_JOURNEYTYPE,
	HOMEPAGE_TRIP_TYPE,
	HOMEPAGE_DEP_AIRPORT,
	HOMEPAGE_ARR_AIRPORT,
	HOMEPAGE_DEP_DATE,
	HOMEPAGE_ARR_DATE,
	HOMEPAGE_ADULT_COUNT,
	HOMEPAGE_CHILD_COUNT,
	HOMEPAGE_INFANTSEAT_COUNT,
	HOMEPAGE_INFANTLAP_COUNT,
	HOMEPAGE_INTERNATIONAL,
	HOMEPAGE_ROOMS,
	HOMEPAGE_CHECK_IN,
	SESSION_BEARER_TOKEN,
	SESSION_JOURNEY_KEY,
	SESSION_FARE_AVAILABILITY_KEY,

	//Bag-O-Tron page Global Variable
	BAG_O_TRON_DEP_BAG_PRICE,
	BAG_O_TRON_RET_BAG_PRICE,
	
	//Flight Availability page Global variable
	AVAILABILITY_DEP_FLIGHT_PRICE,
	AVAILABILITY_RET_FLIGHT_PRICE,
    AVAILABILITY_JOURNEY_FARE,
	AVAILABILITY_DEP_FLIGHT_DETAILS,
	AVAILABILITY_RET_FLIGHT_DETAILS,
	AVAILABILITY_DATE_SEARCH_CRITERIA_OVERWRITE,
	AVAILABILITY_DEP_LEG,
	AVAILABILITY_RET_LEG,
	AVAILABILITY_RED_EYE,
	AVAILABILITY_FS_TOTAL_PRICE,
	AVAILABILITY_9DFC_TOTAL_PRICE,
	AVAILABILITY_MILES_TOTAL_PRICE,
	AVAILABILITY_9DFC_SAVEUPTO_PRICE,
	AVAILABILITY_BOOSTIT_SAVEUPTO_PRICE,
	AVAILABILITY_BUNDLEIT_SAVEUPTO_PRICE,
	
	//Customer Info Page Global Variable
	CUSTOMER_EMAIL,
	
	//Bags page Gobal variable
	BAGS_DEP_BAGS,
	BAGS_RET_BAGS,
	BAGS_TOTAL_PRICE,
	BAGS_DEP_VAT,
	BAGS_RET_VAT,
	BAGS_9DFC_SAVING,

	//seat [age global variable
	SEATS_TOTAL_PRICE,

	//car page global variable
	CAR_NAME,
	CAR_PRICE,
	CAR_DETAILS,
	CAR_DETAILS_CARNET,
	CAR_LOCATION_CARNET,

	//hotel page global variable
	HOTEL_NAME,
	HOTEL_ADDRESS,
	HOTEL_DETAILS,
	
	//Options Page Global Variable
	OPTIONS_FLIGHT_FLEX,
	OPTIONS_SHORTCUT_SECURITY,
	OPTIONS_SHORTCUT_BOARDING,
	OPTIONS_CHECK_IN,

	//payment page Global Variable
	PAYMENT_TRAVELGUARD_PRICE,
	
	//Confirmation page Global variable
	CONFIRMATION_CODE,
	CONFIRMATION_CARNETCAR_CODE,
	CONFIRMATION_HBGHOTEL_CODE,
	CONFIRMATION_LASTNAME,
	CONFIRMATION_TRAVELINSURANCE,
	CONFIRMATION_TRAVELGUARD,
	CONFIRMATION_TOTALPAID,

	RESERVATION_CREDIT_AMOUNT,
	RESERVATION_CREDIT_CODE,
	RESERVATION_VOUCHER_AMOUNT,
	RESERVATION_VOUCHER_CODE,

	//HearthBeat
	HB_ITERATION_COUNT,

	//window Application
	WINDOW_APPPLICATION,
	SKYSPEED_FARE_TYPE;
}
